#!/bin/bash

# Create a virtual environment named 'env' in the current directory
python3 -m venv env

# Activate the virtual environment
source env/bin/activate

# Upgrade pip
pip install --upgrade pip

# Install Django and other necessary packages
pip install Django==4.0.6 \
            asgiref==3.7.2 \
            contourpy==1.2.0 \
            cycler==0.12.1 \
            fonttools==4.47.0 \
            joblib==1.3.2 \
            kiwisolver==1.4.5 \
            matplotlib==3.8.2 \
            mysqlclient==2.1.1 \
            numpy==1.26.2 \
            packaging==23.2 \
            pandas==2.1.4 \
            Pillow==10.1.0 \
            pyparsing==3.1.1 \
            python-dateutil==2.8.2 \
            pytz==2023.3.post1 \
            scikit-learn==1.3.2 \
            scipy==1.11.4 \
            setuptools==69.0.2 \
            six==1.16.0 \
            sqlparse==0.4.4 \
            threadpoolctl==3.2.0 \
            tzdata==2023.3 \
            wheel==0.42.0

echo "Django environment setup complete."
